database:
  dbtype: mysql
  host: 127.0.0.1
  username: root
  password: joker8133xx
  dbname: test
  args: charset=utf8&parseTime=True&loc=Local
  maxIdleConns: 5
  maxOpenConns: 30
  maxLifetime: 30

# debug info warning error panic fatal trace
loglevel: debug
jwt:
  expired: 2
  secret: iwqjhda8232bjgh432cicadasmileiwqj1c2Vybcadashda8gh432cicad232bjgh432cica8232bjgha8232bja