server:
  port: 8080
  swagger: true
database:
  dbType: mysql
  logMode: true
  host: 127.0.0.1:3306
  userName: root
  passWord: joker8133xx
  dbName: test
  args: charset=utf8&parseTime=True&loc=Local
  maxIdleConns: 5
  maxOpenConns: 30
  maxLifetime: 30

log:
  # 日志级别，debug info warn error panic fatal
  level: debug
  path: ./logs/gin-base.log
  # 日志文件最多保存多少个份日志，maxBackups和maxAge都设置为0，则不会删除任何日志文件，全部保留
  maxBackups: 0
  # 文件最多保存多少天
  maxAge: 0
  # 每个日志文件保存的最大尺寸 单位：M，超出后会进行归档压缩
  maxSize: 10
  # 输出方式，console / json
  logFormat: console
  # 是否打印到控制台
  toStd: true

jwt:
  # 有效期，单位：hours
  expired: 2
  secret: iwqjhda823fgK2cicaGasmileiwqj1c2V

pageSize: 10